import { ConfigService } from '../../utils/ConfigService';

const PROFILE_MAP = {
  default: {
    model: ConfigService.GROQ_TEXT_MODEL_FAST,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0.2,
    maxCompletionTokens: 900,
    minCompletionTokens: 260,
    completionRatio: 1.1,
    completionBuffer: 180,
    allowHistory: false,
    maxRecentMessages: 4,
    maxMessageChars: 220,
    maxSummaryChars: 360,
    maxTotalHistoryChars: 900,
    cacheTtlDays: 7,
    responseKind: 'text',
  },
  assistant_general: {
    model: ConfigService.GROQ_TEXT_MODEL_FAST,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0.2,
    maxCompletionTokens: 1300,
    minCompletionTokens: 420,
    completionRatio: 1.35,
    completionBuffer: 260,
    allowHistory: true,
    maxRecentMessages: 4,
    maxMessageChars: 240,
    maxSummaryChars: 420,
    maxTotalHistoryChars: 1100,
    cacheTtlDays: 2,
    responseKind: 'json_envelope',
    disableHistoryAfterFirstAttempt: true,
  },
  assistant_market: {
    model: ConfigService.GROQ_TEXT_MODEL_FAST,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0.1,
    maxCompletionTokens: 900,
    minCompletionTokens: 320,
    completionRatio: 1.1,
    completionBuffer: 180,
    allowHistory: true,
    maxRecentMessages: 3,
    maxMessageChars: 220,
    maxSummaryChars: 300,
    maxTotalHistoryChars: 760,
    cacheTtlDays: 2,
    responseKind: 'json_envelope',
    disableHistoryAfterFirstAttempt: true,
  },
  assistant_workflow: {
    model: ConfigService.GROQ_TEXT_MODEL_FAST,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0.15,
    maxCompletionTokens: 950,
    minCompletionTokens: 360,
    completionRatio: 1.2,
    completionBuffer: 220,
    allowHistory: true,
    maxRecentMessages: 3,
    maxMessageChars: 220,
    maxSummaryChars: 320,
    maxTotalHistoryChars: 760,
    cacheTtlDays: 2,
    responseKind: 'json_envelope',
    disableHistoryAfterFirstAttempt: true,
  },
  assistant_image: {
    model: ConfigService.GROQ_VISION_MODEL,
    fallbackModel: ConfigService.GROQ_VISION_MODEL,
    temperature: 0.1,
    maxCompletionTokens: 900,
    minCompletionTokens: 320,
    completionRatio: 1,
    completionBuffer: 180,
    allowHistory: false,
    cacheTtlDays: 14,
    responseKind: 'json_envelope',
  },
  auto_agronomist: {
    model: ConfigService.GROQ_TEXT_MODEL_STRUCTURED,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0,
    maxCompletionTokens: 340,
    minCompletionTokens: 150,
    completionRatio: 0.8,
    completionBuffer: 100,
    allowHistory: false,
    cacheTtlDays: 3,
    responseKind: 'json_envelope',
  },
  schedule: {
    model: ConfigService.GROQ_TEXT_MODEL_FAST,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0.15,
    maxCompletionTokens: 1800,
    minCompletionTokens: 950,
    completionRatio: 1.5,
    completionBuffer: 400,
    allowHistory: false,
    cacheTtlDays: 14,
    responseKind: 'json_envelope',
  },
  translation: {
    model: ConfigService.GROQ_TRANSLATION_MODEL,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0,
    maxCompletionTokens: 1000,
    minCompletionTokens: 140,
    completionRatio: 0.9,
    completionBuffer: 110,
    allowHistory: false,
    cacheTtlDays: 30,
    responseKind: 'json_array',
  },
  farm_profile: {
    model: ConfigService.GROQ_TEXT_MODEL_STRUCTURED,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0,
    maxCompletionTokens: 850,
    minCompletionTokens: 320,
    completionRatio: 1,
    completionBuffer: 180,
    allowHistory: false,
    cacheTtlDays: 30,
    responseKind: 'json_object',
  },
  impact: {
    model: ConfigService.GROQ_TEXT_MODEL_STRUCTURED,
    fallbackModel: ConfigService.GROQ_TEXT_MODEL_FAST,
    temperature: 0,
    maxCompletionTokens: 260,
    minCompletionTokens: 120,
    completionRatio: 0.8,
    completionBuffer: 60,
    allowHistory: false,
    cacheTtlDays: 7,
    responseKind: 'json_object',
  },
};

export const resolveAIRequestProfile = (feature = 'default', overrides = {}) => {
  const base = PROFILE_MAP[feature] || PROFILE_MAP.default;
  return {
    ...PROFILE_MAP.default,
    ...base,
    ...overrides,
  };
};
