export const EVENT_TOPICS = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_RESOLVED: 'TASK_RESOLVED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  SENSOR_DATA_RECEIVED: 'SENSOR_DATA_RECEIVED',
  NETWORK_STATUS_CHANGED: 'NETWORK_STATUS_CHANGED',
  LANGUAGE_CHANGED: 'LANGUAGE_CHANGED',
  SENSOR_THRESHOLD_EXCEEDED: 'SENSOR_THRESHOLD_EXCEEDED',
  NODE_CONNECTION_LOST: 'NODE_CONNECTION_LOST',
  NODE_CONNECTION_RESTORED: 'NODE_CONNECTION_RESTORED',
  WEATHER_ALERT_CREATED: 'WEATHER_ALERT_CREATED',
  BUYER_MATCH_FOUND: 'BUYER_MATCH_FOUND',
  TRANSACTION_COMPLETED: 'TRANSACTION_COMPLETED',
  IMPACT_EVENT_CREATED: 'IMPACT_EVENT_CREATED'
};
